name: Deploy lambdas
description: Deploy lambdas to AWS from the specified directory
inputs:
  directory:
    type: string
    required: true
  LAMBDA_ROLE_ARN:
    description: 'ARN of the role to assign to the lambdas'

runs:
  using: composite
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install AWS Lambda tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Deploy event lambdas
      shell: bash
      run: |
        for LAMBDA_DIR in ${{ inputs.directory }}/*; do
          if [ -d "$LAMBDA_DIR" ]; then
            echo "Deploying function in $LAMBDA_DIR"
            cd $LAMBDA_DIR
            dotnet lambda deploy-function --region eu-west-1 --function-name $(basename $LAMBDA_DIR) --function-role ${{ inputs.LAMBDA_ROLE_ARN }}
            cd ..
          fi
        done
